### PR TITLE
 Update deployment for dask-2.2

### PR DESCRIPTION
**Pull request by mrocklin**
Dask has undergone some significant changes in how we deploy.

1.  Keywords like bokeh-foo have been replaced with dashboard-foo
2.  We use async def functions now rather than Tornado gen.coroutines.
    As a result functions like scheduler.start() have to be awaited to have
    impact
3.  We've moved some of the logic into the main classes, removing some need for
    extra handling outside of the Worker/Scheduler calls.
4.  ...

This commit updates dask-mpi to be aware of these changes.
In doing so it also removes the common.py file.

Note, no effort has been made so far for backwards compatibility.
I've also lost the dashboard-prefix keyword in doing this hastily.

### CODE REVIEW

**Comment by mrocklin** [comment]
OK, I think that this is now in a stable state.  The opempi tests failed during conda installation on this run, but worked well on the previous test, and not much has changed.  It seems that I don't have sufficient circle-ci permissions to restart the build (which I'm personally quite fine with :) )

This PR does make some negative changes though.  It removes keywords like `--nanny-port` and `--worker-bokeh-port` which, I claim, are of dubious value.  I can add them back in, but I'm a bit curious why they were introduced over others, which are not yet supported.

I'm running into this challenge of how to pass through keyword arguments well.  If possible I think that we should aim for more of a passthrough solution rather than having to special-case each option.

Anyway, @kmpaul @andersy005 , this could use review if you have a moment.

**Comment by andersy005** [comment]
> It seems that I don't have sufficient circle-ci permissions to restart the build (which I'm personally quite fine with :) )

Hmm... This seems strange since you have admin permissions on the Github repo. My understanding is that CircleCI leverages GitHub’s permissions to determine users access.

**Comment by andersy005** [comment]
@mrocklin, I may have serendipitously fixed the Openmpi tests issue  :) 

> but I'm a bit curious why they were introduced over others, which are not yet supported.

@kmpaul might be the right person to expand on this. 

> 

Overall, everything looks good to me. Regarding the lack of backwards compatibility, I think that this is perfectly okay when considering new changes introduced in dask and distributed `>=2.0`. We should perhaps cut a `dask-mpi-2.0` release after this PR.

**Comment by mrocklin** [comment]
> We should perhaps cut a dask-mpi-2.0 release after this PR.

For the dask/dask and dask/distributed libraries we started using the same version number recently.  So whenever dask/distributed releases it chooses the current version number of dask/dask, if greater.

**Comment by mrocklin** [comment]
(so you might consider releasing the next version as dask-mpi version 2.2)

**Comment by andersy005** [comment]
> I'm running into this challenge of how to pass through keyword arguments well. If possible I think that we should aim for more of a passthrough solution rather than having to special-case each option.

Should we address this issue in a separate PR?

**Comment by mrocklin** [comment]
Yes, I think so.  Hopefully I'll also come up with a generic solution in
the dask/distributed codebase that dask-mpi can steal

**Comment by andersy005** [comment]
@mrocklin, @kmpaul just checking in. Any other comments or concerns prior merging this PR? I am planning on merging this tomorrow if there aren't any objections.

**Comment by mrocklin** [comment]
I was waiting until the dask 2.2 release occurs and then I was planning on
merging, bumping requirements, and releasing.  I'm happy to take this over
for this process if you like (I'm doing this for a lot of the dask-foo
projects this time around)

**Comment by andersy005** [comment]
>  I'm happy to take this over for this process if you like (I'm doing this for a lot of the dask-foo
projects this time around)

Sure! I noticed your recent activity in dask-foo projects and thought I would relieve you of this one, but it sounds like you are having fun -:)

**Pull request merged**
