### PR TITLE
CI improvements + Python 2.7 Compatibility

### LINKED ISSUE #7: Enable CircleCI testing
I have a `.circleci/config.yml` file in place, but this should be reviewed before deployment.

Also, we might need the recent changes to `dask/distributed` to be released before we enable CI.

### PR DESCRIPTION
**Pull request by andersy005**
This PR closes #7
- [x] Allow CircleCI to run builds for PRs from folks
- [x] Update docker image to continuumio/miniconda:latest
- [x] Add CircleCI, Codecov badges
- [x] Add backport of the subprocess module from Python 3 for use on 2.x

### CODE REVIEW

**Comment by andersy005** [comment]
@kmpaul, tests are now running on CircleCI. However, `dask_mpi/tests/test_core.py` seems to be hanging (https://circleci.com/gh/dask/dask-mpi/9). Do you happen to know the reason behind this issue?

**Comment by andersy005** [comment]
@kmpaul, tests are failing on both 2.7 and 3.6. To make sure that this PR does not diverge from its original purpose (CI improvements), I am going to look into the test failure in a separate PR.

**Comment by kmpaul** [comment]
Sounds good.  You will need to modify the tests to clone the master branch of `distributed` and `pip install -e ../path/to/distributed` in order for this code to work.

**Comment by kmpaul** [comment]
Make sure you add a step to clone the latest master branch of `distributed` before the tests run.

**Pull request merged**
