### PR TITLE
Add GitHub workflow for automated PyPI release

### PR DESCRIPTION
**Pull request by kmpaul**

### CODE REVIEW

**Comment by kmpaul** [comment]
@jacobtomlinson:  So, I just realized that I don't have admin privileges on this repo.  😄   So, I can't add an API token on the dask/dask-mpi repo.  I can add you to the PyPI project, too, if you share your PyPI username with me.

**Comment by jacobtomlinson** [comment]
@kmpaul I've made you an admin here, that definitely sounds like an oversight. I'm `jacobtomlinson` on PyPI too :).

**Comment by kmpaul** [comment]
@jacobtomlinson:  Tried to invite you to the PyPI project, but it says that username (`jacobtomlinson`) was not found....?

**Comment by kmpaul** [comment]
I've created the necessary secret for this action to work on the main repo (here), so I'm going to merge to test.

**Comment by kmpaul** [comment]
@jacobtomlinson:  I found your PyPI username and invited you to the PyPI project.  If you don't see the invitation, let me know.

**Comment by jacobtomlinson** [comment]
Ah yeah I always forget about the `.`. Thanks @kmpaul.

**Comment by jacobtomlinson** [comment]
Looks like this went well!

https://github.com/dask/dask-mpi/runs/4191894829?check_suite_focus=true

**Comment by kmpaul** [comment]
Yes.  The action job name is terrible.  😄  But I fixed that.  Should be fine for future uses.

**Pull request merged**
