### PR TITLE
Add OpenMPI jobs to CircleCI workflow

### PR DESCRIPTION
**Pull request by andersy005**

### CODE REVIEW

**Comment by kmpaul** [comment]
@andersy005 To avoid too much frustration waiting for CircleCI to finish tests, you might try running a Docker container on your laptop to reproduce the environment.

**Comment by andersy005** [comment]
@kmpaul, Thank you for the tip! For the time being, I've ssh'ed into CircleCI docker containers. Will resort to a local container once my patience is exhausted :)

**Comment by andersy005** [comment]
@kmpaul, tests are now passing for both OpenMPI and MPICH.

**Comment by andersy005** [comment]
@mrocklin, Thank you for the suggestion! I just added it, and tests are cleaner than they were with `cmd` branching. Let me know what you think.

**Pull request merged**
