### PR TITLE
Fixes: ImportError: cannot import name 'uri_from_host_port'.

### PR DESCRIPTION
**Pull request by muammar**
There is an ImportError of 'uri_from_host_port' function. This PR fixes it.

### CODE REVIEW

**Comment by andersy005** [comment]
Thanks for the PR @muammar! 

> There is an ImportError of 'uri_from_host_port' function

A month ago, this PR https://github.com/dask/distributed/pull/2667 introduced new changes that break dask-mpi when using latest version of distributed. This fix fully works if you are on the latest version of `distributed`. Per https://github.com/dask/dask-mpi/blob/master/environment.yml#L4, `dask-mpi` requires `distributed=1.25.2` . 

As pointed out in https://github.com/dask/dask-mpi/issues/30, `dask-mpi` is very strict when it comes to its dependencies versions. For this fix to fully address the import issue, `distributed` version will have to be pinned to the latest version, and a few changes will have to be made in `dask-mpi` codebase.

Ccing @kmpaul, @mrocklin

**Comment by muammar** [comment]
@andersy005  Thank you very much for your reply, it is very useful.

> Thanks for the PR @muammar!
> 
> > There is an ImportError of 'uri_from_host_port' function
> 
> A month ago, this PR [dask/distributed#2667](https://github.com/dask/distributed/pull/2667) introduced new changes that break dask-mpi when using latest version of distributed. This fix fully works if you are on the latest version of `distributed`. Per https://github.com/dask/dask-mpi/blob/master/environment.yml#L4, `dask-mpi` requires `distributed=1.25.2` .
> 

 Your assumption is right, I installed `distributed` with `setup.py` because there are changes in that version that I need to run my program.

> As pointed out in #30, `dask-mpi` is very strict when it comes to its dependencies versions. For this fix to fully address the import issue, `distributed` version will have to be pinned to the latest version, and a few changes will have to be made in `dask-mpi` codebase.
> 
> Ccing @kmpaul, @mrocklin

Now I wonder -- how often are you syncing with respect to latest `distributed` version?

**Comment by kmpaul** [comment]
@muammar If by "syncing" you mean "testing with the latest version of `distributed` and modifying `dask-mpi` to meet the `distributed` API," the answer is, "We really aren't syncing."  And we need to do that.  I think we need to try removing the `distributed` version pinning and fix our API to match.

Unfortunately, when we encountered our first problem with changing `distributed` API, I was too swamped to fix the problem properly.  So, I pinned to the previous version with the intention of getting back to it.  I may finally have time to get back to it, but I would greatly appreciate any help you might be able to provide.

**Comment by muammar** [comment]
Hi @kmpaul 

> @muammar If by "syncing" you mean "testing with the latest version of `distributed` and modifying `dask-mpi` to meet the `distributed` API," the answer is, "We really aren't syncing." And we need to do that. I think we need to try removing the `distributed` version pinning and fix our API to match.
> 

That's exactly what I meant --  changing the codebase so that `dask_mpi` is compatible with the latest `distributed` package. 

> Unfortunately, when we encountered our first problem with changing `distributed` API, I was too swamped to fix the problem properly. So, I pinned to the previous version with the intention of getting back to it. I may finally have time to get back to it, but I would greatly appreciate any help you might be able to provide.

I would be glad to offer any help needed. Right now, I submitted a calculation in Cori@NERSC using the small change included with this PR. I will start posting errors I find when doing so with the hope we can get this solved.

**Comment by muammar** [comment]
I submitted a calculation and now I wonder if Python's `logging` module works well with `mpi4py`. That is because I cannot see any of the logging files that were supposed to be created when running this on Cori. I  will keep you posted.

**Comment by kmpaul** [comment]
@muammar Yes.  I've experienced difficulties with MPI capturing output from processing when `logging` is used.  They do not seem to work together terribly well.

**Comment by kmpaul** [comment]
@muammar I do not get the import error you encountered with `distributed` version 1.28.1.  What version of `distributed` were you using when you encountered this import error?

On an unrelated note, I (hopefully) have a fix (#33) for all of this, that will fix the syncing-to-the-most-recent-distributed problems, too.

**Comment by muammar** [comment]
Hi @kmpaul, 

> @muammar Yes. I've experienced difficulties with MPI capturing output from processing when `logging` is used. They do not seem to work together terribly well.

Thank you for your prompt reply. This was very useful to confirm that the problem I was having with logging was due to the python logging module and not something else. The thing is that my script seemed to be running without dying with the PR I submitted but I cannot tell what is doing as the logging module is not writing anything to file. 

> @muammar I do not get the import error you encountered with `distributed` version 1.28.1. What version of `distributed` were you using when you encountered this import error?
> 

These are the versions I am using at Cori:

```
>>> import dask
>>> import distributed
>>> import dask_mpi
>>> dask.__version__
'1.2.2'
>>> distributed.__version__
'1.28.1+56.g2ba70b31'
>>> dask_mpi.__version__
'1.0.2'
>>> 
```
My `distributed` version is basically the `HEAD` of the `master` branch because I need some changes that are not present in `1.2.8.1`.

> On an unrelated note, I (hopefully) have a fix (#33) for all of this, that will fix the syncing-to-the-most-recent-distributed problems, too.

That is great! I really appreciate your fast replies. Would you have a test example that I could run here?

**Comment by kmpaul** [comment]
@muammar I am sorry, but I am about to jump on a plane, so I will be out of touch for a while. The best way to test is by running the pytest suite. The “test_core.py” test is where the batch mode tests are located. You can also test just by running:

    mpirun -np 4 python dask_mpi/tests/core_basic.py

**Comment by kbarros** [comment]
I have not been able to get dask-mpi to work, even with this fork. I tried

`mpirun -np 4 python dask_mpi/tests/core_basic.py`

and it fails with a timeout. The `pytest dask_mpi` also hangs after printing `dask_mpi/tests/test_cli.py`.

In case it's relevant, I installed the default versions of mpi4py, dask, and distributed from pip.

```
In [3]: dask.__version__                                                                                                                                                        
Out[3]: '2.0.0'

In [4]: distributed.__version__                                                                                                                                                 
Out[4]: '2.0.1'
```

**Comment by andersy005** [comment]
@kbarros, I will look more into this, and will get back to you

**Comment by chiaral** [comment]
With @rabernat, we are trying to use dask-mpi on cheyenne. We have the (near) latest versions of everything:

- dask v 2.5.2.
- distributed v 2.5.2
- dask-mpi v 1.0.3

We are getting this exact same error, despite claims that it has been fixed.

Our batch script is

```bash
#!/bin/bash
#PBS -N dask-mpi
#PBS -q economy
#PBS -A UCLB0022
#PBS -l select=2:ncpus=36:mpiprocs=1
#PBS -l walltime=01:00:00
#PBS -j oe
#PBS -m abe

# Qsub template for UCAR CHEYENNE
# Scheduler: PBS

# This writes a scheduler.json file into your home directory
# You can then connect with the following Python code
# >>> from dask.distributed import Client
# >>> client = Client(scheduler_file='~/scheduler.json')

source activate pangeo

# debugging stuff
which python
python -c 'import dask; print(dask.__version__)'
dask-scheduler --version
dask-mpi

rm -f scheduler.json
mpirun -np 2 dask-mpi \
    --scheduler-file ~/scheduler.json \
    --nthreads 36 \ 
    --interface ib0
```

In the error log we see

```
2.5.2
dask-scheduler, version 2.5.2
Warning: Permanently added the ECDSA host key for IP address '10.148.14.116' to the list of known hosts.
Attaching 35536 to 8937069.chadmin1.ib0.cheyenne.ucar.edu
Traceback (most recent call last):
  File "/glade/u/home/clepore/miniconda3/envs/pangeo/bin/dask-mpi", line 7, in <module>
    from dask_mpi.cli import go
  File "/glade/u/home/clepore/miniconda3/envs/pangeo/lib/python3.6/site-packages/dask_mpi/__init__.py", line 1, in <module>
    from .core import initialize
  File "/glade/u/home/clepore/miniconda3/envs/pangeo/lib/python3.6/site-packages/dask_mpi/core.py", line 12, in <module>
    from .common import (
  File "/glade/u/home/clepore/miniconda3/envs/pangeo/lib/python3.6/site-packages/dask_mpi/common.py", line 5, in <module>
    from distributed.cli.utils import uri_from_host_port
ImportError: cannot import name 'uri_from_host_port'
Traceback (most recent call last):
  File "/glade/u/home/clepore/miniconda3/envs/pangeo/bin/dask-mpi", line 7, in <module>
    from dask_mpi.cli import go
  File "/glade/u/home/clepore/miniconda3/envs/pangeo/lib/python3.6/site-packages/dask_mpi/__init__.py", line 1, in <module>
    from .core import initialize
  File "/glade/u/home/clepore/miniconda3/envs/pangeo/lib/python3.6/site-packages/dask_mpi/core.py", line 12, in <module>
    from .common import (
  File "/glade/u/home/clepore/miniconda3/envs/pangeo/lib/python3.6/site-packages/dask_mpi/common.py", line 5, in <module>
    from distributed.cli.utils import uri_from_host_port
ImportError: cannot import name 'uri_from_host_port'
/var/spool/pbs/mom_priv/jobs/8937069.chadmin1.ib0.cheyenne.ucar.edu.SC: line 29: --interface: command not found
```

**Comment by chiaral** [comment]
FYI we were able to get past this by installing dask-mpi from git master.

Looks like a release is needed.

**Comment by andersy005** [comment]
@chiaral 


> Looks like a release is needed.

While looking at your previous comment, I noticed that you were running `dask-mpi v 1.0.3`. The latest release of dask-mpi is v2.0.0 (released in August), and it's available on [conda-forge](https://anaconda.org/conda-forge/dask-mpi) and PyPI.

**Comment by rabernat** [comment]
@andersy005 - I see that now.

The weird thing is that we did a fresh `conda install -c conda-forge dask-mpi` for this project. I wonder why we didn't get v2.0.0? Also, I checked the [github releases](https://github.com/dask/dask-mpi/releases) page and got the impression that 1.3.0 was indeed the latest release. (I see you have updated it now.) So something weird was going on.

Anyway, sorry for then noise and thanks for the update!

**Pull request closed without merging**
