### PR TITLE
Add support for use as part of a wider MPI process

### PR DESCRIPTION
**Pull request by joezuntz**
The current version of the code always uses MPI_COMM_WORLD as the communicator and calls sys.exit on some processes when the client process exits python.

This change makes it possible to use dask-mpi for part of an MPI process but then return to the original MPI workflow once it is complete. It requires the user to manually call `send_close_signal` from the client process, and to use a returned value indicating whether the process is the client or not.

### CODE REVIEW

**Comment by joezuntz** [comment]
The test failures shown seem to be part of the original code that is not affected by the changes I've made, and are associated with a timing test. I guess this might be associated with github actions having slowed down since these were written?

**Comment by kmpaul** [comment]
@joezuntz:  Can you pull recent updates from the `main` branch and see what tests pass/fail?

**Comment by joezuntz** [comment]
I just did this but it seems to show only a single change, to cli.py - is that what you expected?

**Comment by joezuntz** [comment]
Also it says it's "awaiting approval" now: "First-time contributors need a maintainer to approve running workflows"

**Comment by kmpaul** [comment]
@joezuntz:  Yay!  Tests pass, and the failures had nothing to do with your code.

**Comment by kmpaul** [comment]
@joezuntz:  Is this ready to merge, then?

**Comment by joezuntz** [comment]
Yep, I think good to go - thanks!

**Comment by kmpaul** [comment]
Thanks @joezuntz!

**Pull request merged**
