### PR TITLE
Experimental update to use new Distributed Runner base class

### PR DESCRIPTION
**Pull request by jacobtomlinson**
This project is awesome and really neatly solves the issue of bootstrapping a Dask cluster on an MPI system.

There are other batch systems which do not use MPI that could make use of this method.

I've raised dask/distributed#4710 which adds a new `Runner` base class to `distributed` which simplifies the implementation of this kind of cluster bootstrapping.

This PR is an example of how it could be used to re-implement dask-mpi.

It introduces an `MPIRunner` class which is used in place of the `initialize` function to create the cluster. It can be used as a context manager and more closely follows the `Cluster` pattern seen in other Dask deployment projects.

Instead of invoking `initialize` which does everything under the hood, including silently updating the scheduler address in the Dask config, we can use a context manager to do things explicitly.

```python
from distributed import Client
from dask_mpi import MPIRunner

with MPIRunner() as runner:  # Only rank 1 executes the code within the context manager, everything else blocks here running the scheduler and workers
    with Client(runner) as c:

        # Do client things
```

I've also updated the CLI and `initialize` to use `MPIRunner` under the hook to reduce code duplication and keep backward compatibility.

```python
from distributed import Client
from dask_mpi import initialize

initialize()  # Creates an MPIRunner and sets the Dask config

with Client(runner) as c:

    # Do client things
```

My hope here is to be able to use the concepts that I've upstreamed into `Runner` in other projects like `dask-cloudprovider`.

### CODE REVIEW

**Comment by kmpaul** [comment]
@jacobtomlinson This looks awesome!  I'll see if I can look at this this week.  Currently, I'm in the middle of moving houses, so it might take a bit.

**Comment by jacobtomlinson** [comment]
Thanks @kmpaul. Things are a little in flux here as there is an ongoing discussion about how to support this case more broadly upstream in distributed. I'll convert this to a draft for now.

Good luck with the house move!

**Comment by kmpaul** [comment]
@jacobtomlinson:  Thanks!  I've subscribed to dask/distributed#4710 to follow along.

**Comment by kmpaul** [comment]
I pushed some changes from main into your branch, but I'm not sure I'm using the right version of distributed for the tests.  I realize this is a draft, but hopefully the upstream changes can make testing this a little easier.

**Comment by jacobtomlinson** [comment]
I think the discussion in dask/distributed#4710 ended up deciding not to go down this path, so I'm going to close this out.

**Pull request closed without merging**
